#!/usr/bin/lua

require "read_status_nagios"
require "html"

status = read_status_nagios()

print ("Nagios version: ", status.info[1].version)
print ("Number of servicestatus: ", table.getn(status.servicestatus))
print ("Contact name: ", status.contactstatus[1].contact_name)

