# User (contacts) config file automatically generated by ITVision

contact {
	name   = "Jose Antonio",
	location  = "VERTO",
	depto  = "TECH",
	tel_1  = "2121329900",
	tel_2  = "-",
	cel    = "02194336088",
	e_mail = "jantonio@verto.com.br",
	sms    = "02194336088@clarotorpedo.com.br",
	turno  = "-",
	applications = {'[Infra] Palacio','[Infra] Serpro','[Infra] Maracana','Internet','Correio','DNS Interno','[Infra] CAERJ','[Infra] NC','[Infra] PROXY' , 'M-CLIPPING'},
}

contact {
	name   = "Jose Augusto Cardoso",
	location  = "VERTO",
	depto  = "TECH",
	tel_1  = "-",
	tel_2  = "-",
	cel    = "-",
	e_mail = "jcardoso@verto.com.br",
	sms    = "-",
	turno  = "-",
	applications = {'[Infra] Palacio','[Infra] Serpro','[Infra] Maracana','Internet','Correio','DNS Interno','[Infra] CAERJ','[Infra] NC'},
}

contact {
	name   = "Paulo Coelho",
	location  = "PRODERJ",
	depto  = "",
	tel_1  = "",
	tel_2  = "-",
	cel    = "-",
	e_mail = "pccoelho@proderj.rj.gov.br",
	sms    = "-",
	turno  = "-",
	applications = {'Internet','Correio','DNS Interno','DNS Externo','Web Sites'},
}

contact {
	name   = "Sergio Chiapetta",
	location  = "PRODERJ",
	depto  = "",
	tel_1  = "",
	tel_2  = "-",
	cel    = "-",
	e_mail = "schiapett@proderj.rj.gov.br",
	sms    = "-",
	turno  = "-",
	applications = {'[Infra] Palacio','[Infra] Serpro','[Infra] Maracana','Internet','Correio','DNS Interno','[Infra] CAERJ','[Infra] NC' , 'M-CLIPPING'},
}

contact {
	name   = "GPG",
	location  = "Palacio",
	depto  = "",
	tel_1  = "",
	tel_2  = "-",
	cel    = "-",
	e_mail = "gpg@proderj.rj.gov.br",
	sms    = "-",
	turno  = "-",
	applications = {'[Infra] Palacio'},
}

contact {
	name   = "MClip",
	location  = "PRODERJ",
	depto  = "",
	tel_1  = "",
	tel_2  = "-",
	cel    = "-",
	e_mail = "mclipping-clipadora-alertas@proderj.rj.gov.br",
	sms    = "-",
	turno  = "-",
	applications = {'M-CLIPPING'},
}

contact {
	name   = "Daniel de Albuquerque",
	location  = "VERTO",
	depto  = "TECH",
	tel_1  = "2125295081",
	tel_2  = "-",
	cel    = "-",
	e_mail = "daniel.dalb@gmail.com",
	sms    = "-",
	turno  = "-",
	applications = {'[Infra] Palacio','[Infra] Serpro','[Infra] Maracana','Internet','Correio','DNS Interno','[Infra] CAERJ','[Infra] NC','[Infra] PROXY'},
}

contact {
	name   = "CEOP",
	location  = "CEOP",
	depto  = "PRODERJ",
	tel_1  = "-",
	tel_2  = "-",
	cel    = "-",
	e_mail = "itvision@proderj.rj.gov.br",
	sms    = "-",
	turno  = "-",
	applications = {'Correio' , 'DNS Externo' , 'DNS Interno' , '[Infra] CAERJ' , '[Infra] CIC' , '[Infra] Collocation' , '[Infra] Correio' , '[Infra] Datacenter' , '[Infra] Discado' , '[Infra] Internet' , '[Infra] Maracana' , '[Infra] NC' , '[Infra] Palacio' , '[Infra] PROXY' , '[Infra] SEEDUC' , '[Infra] Serpro' , '[Infra] Servidores Linux' , '[Infra] Servidores Windows' , 'Internet' , 'INTRAGOV' , 'SEEDUC' , 'SEPLAG' , 'Web Sites' , 'M-CLIPPING'},
}

